"""
Data loader for AC Optimal Power Flow (ACOPF) datasets.

This module loads optimization problems generated by Generate_DCOPF.jl
where:
- X (input) = Demand vectors (concatenated P and Q for each bus)
- Y (output) = Optimal AC objective values (scalar)

Unlike DCPM (which is convex), ACPM is NON-CONVEX due to the nonlinear
AC power flow equations. This requires a standard neural network instead
of an Input Convex Neural Network.
"""

using BSON
using Statistics
using Random

"""
    load_acpm_data(file_path::String)

Load ACPM dataset from BSON file generated by Generate_DCOPF.jl.

# Arguments
- `file_path::String`: Path to BSON file containing the dataset

# Returns
A dictionary with keys:
- `"Demand"`: Matrix (n_samples, 2*n_buses) - Input features
- `"ObjAC"`: Vector (n_samples,) - Optimal AC objective values
- `"DispatchAC"`: Matrix (n_samples, n_generators) - Optimal AC dispatch
- `"TimeAC"`: Vector (n_samples,) - AC solution times
- `"ObjDC"`: Vector (n_samples,) - Optimal DC objective values (for comparison)
- `"DispatchDC"`: Matrix (n_samples, n_generators) - Optimal DC dispatch
- `"TimeDC"`: Vector (n_samples,) - DC solution times
- `"n_valid"`: Number of valid samples

# Example
```julia
data = load_acpm_data("test_systems/data_pglib_opf_case118_ieee.bson")
X = data["Demand"]
Y = data["ObjAC"]  # AC objective (non-convex)
```
"""
function load_acpm_data(file_path::String)
    if !isfile(file_path)
        error("File not found: $file_path")
    end

    data = BSON.load(file_path)

    # Handle nested structure (data saved as Dict("results" => Dict(...)))
    if haskey(data, :results) || haskey(data, "results")
        data = haskey(data, :results) ? data[:results] : data["results"]
    end

    # Validate required keys for ACPM
    required_keys = ["Demand", "ObjAC"]
    for key in required_keys
        if !haskey(data, key) && !haskey(data, Symbol(key))
            error("Missing required key '$key' in BSON file")
        end
    end

    # Convert Symbol keys to String keys if needed
    result = Dict{String, Any}()
    for (k, v) in pairs(data)
        key_str = isa(k, Symbol) ? String(k) : k
        result[key_str] = v
    end

    @info "Loaded ACPM data from $file_path"
    @info "  Samples: $(size(result["Demand"], 1))"
    @info "  Features: $(size(result["Demand"], 2))"
    @info "  AC Objective range: [$(minimum(result["ObjAC"])), $(maximum(result["ObjAC"]))]"

    # Validate problem is non-convex (check AC-DC gap)
    if haskey(result, "ObjDC")
        @info "  DC Objective range: [$(minimum(result["ObjDC"])), $(maximum(result["ObjDC"]))]"

        ac_vals = result["ObjAC"]
        dc_vals = result["ObjDC"]

        # Compute AC-DC gap percentage
        ac_dc_gap_pct = abs.((ac_vals .- dc_vals) ./ ac_vals) .* 100
        avg_gap = mean(ac_dc_gap_pct)
        max_gap = maximum(ac_dc_gap_pct)

        @info "AC-DC Gap Analysis:"
        @info "  Average gap: $(round(avg_gap, digits=3))%"
        @info "  Max gap: $(round(max_gap, digits=3))%"

        if avg_gap < 0.1
            @warn "AC-DC gap is very small ($avg_gap%) - problem may be nearly convex!"
        end

        if avg_gap < 0.001
            error("AC and DC objectives are virtually identical - wrong data mode or DC-only data loaded!")
        end
    elseif !haskey(result, "ObjDC")
        @warn "DC objectives not found - cannot verify problem is non-convex"
    end

    return result
end

"""
    prepare_acpm_dataset(file_path::String;
                         train_ratio=0.8,
                         normalize_method=:standardize,
                         shuffle=true,
                         seed=42)

Complete pipeline to load and prepare ACPM data for training.

# Arguments
- `file_path`: Path to BSON file
- `train_ratio`: Fraction for training set
- `normalize_method`: :standardize, :minmax, or :none
- `shuffle`: Whether to shuffle data
- `seed`: Random seed

# Returns
Named tuple with:
- `X_train, Y_train`: Training data
- `X_test, Y_test`: Test data
- `scaler_X, scaler_Y`: Normalization parameters
- `n_features`: Number of input features
- `raw_data`: Original data dict

# Example
```julia
dataset = prepare_acpm_dataset("test_systems/data_case118.bson")
model = StandardNN(dataset.n_features, 1; hidden_sizes=[200, 200])
train!(model, dataset.X_train, dataset.Y_train, 100;
       X_test=dataset.X_test, y_test=dataset.Y_test,
       is_convex=false)  # IMPORTANT: Set is_convex=false for ACPM
```
"""
function prepare_acpm_dataset(file_path::String;
                              train_ratio=0.8,
                              normalize_method=:standardize,
                              shuffle=true,
                              seed=42)
    # Load raw data
    raw_data = load_acpm_data(file_path)
    X_raw = raw_data["Demand"]
    Y_raw = raw_data["ObjAC"]  # Use AC objective (non-convex)

    # Normalize (reuse functions from dcopf_loader)
    X_norm, Y_norm, scaler_X, scaler_Y = normalize_data(X_raw, Y_raw; method=normalize_method)

    # Split
    X_train, Y_train, X_test, Y_test = split_data(X_norm, Y_norm;
                                                   train_ratio=train_ratio,
                                                   shuffle=shuffle,
                                                   seed=seed)

    n_features = size(X_train, 2)

    @info "ACPM Dataset prepared:"
    @info "  Training samples: $(size(X_train, 1))"
    @info "  Test samples: $(size(X_test, 1))"
    @info "  Features: $n_features"
    @info "  Normalization: $normalize_method"
    @info "  Problem type: NON-CONVEX (AC Power Flow)"

    return (
        X_train=X_train,
        Y_train=Y_train,
        X_test=X_test,
        Y_test=Y_test,
        scaler_X=scaler_X,
        scaler_Y=scaler_Y,
        n_features=n_features,
        raw_data=raw_data
    )
end
