"""
# Outer Approximation Counterfactual Generation on DCOPF Data

## Overview
This example demonstrates generating counterfactuals using the Outer Approximation (OA)
algorithm on DC Optimal Power Flow (DCOPF) data with a trained FICNN model.

## What This Script Does
1. Load a pre-trained FICNN model on DCOPF data
2. Load the DCOPF test dataset
3. Select an interesting test instance
4. Define a counterfactual target (e.g., reduce cost by 20%)
5. Generate counterfactual using OA algorithm
6. Validate and visualize results
7. Compare factual vs counterfactual predictions

## Prerequisites
- Trained FICNN model (run `julia src/train_dcopf.jl` first)
- DCOPF dataset (generated by `julia icnn/data/Generate_DCOPF.jl`)

## Usage
From repository root:
```bash
julia examples/generate_counterfactual_oa_example.jl
```

## OA Algorithm Benefits
- **Fast**: No hidden layer variables, only OA cuts
- **Scalable**: Linear growth in constraints per iteration
- **Guaranteed**: Global optimality for convex ICNNs
- **Efficient**: Exploits convexity structure
"""

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

# Load ICNN module
include("../icnn/ICNN.jl")
using .ICNN

# Load counterfactual generation utilities
include("../counterfactuals/utils/gradient_utils.jl")
include("../counterfactuals/algorithms/outer_approximation.jl")

using Printf
using Statistics
using BSON

println("=" ^ 80)
println("OUTER APPROXIMATION COUNTERFACTUAL GENERATION - DCOPF EXAMPLE")
println("=" ^ 80)
println()

# ============================================================================
# STEP 1: Load Trained FICNN Model
# ============================================================================

println("STEP 1: Loading trained FICNN model")
println("-" ^ 80)

# Path to trained model (adjust if needed)
model_path = joinpath(@__DIR__, "..", "tmp", "dcopf_experiment", "best_model.bson")

if !isfile(model_path)
    println("ERROR: No trained model found at:")
    println("  $model_path")
    println()
    println("Please train a model first by running:")
    println("  julia src/train_dcopf.jl")
    println()
    println("This will train a FICNN on DCOPF data and save it to:")
    println("  tmp/dcopf_experiment/best_model.bson")
    println()
    println("Training typically takes a few minutes with default settings.")
    exit(1)
end

println("Loading model from: $model_path")

# Load the model
model_data = BSON.load(model_path)
model = model_data[:model]

println("✓ Model loaded successfully!")
println()
println("Model architecture:")
println("  Type: $(typeof(model))")
println("  Input features: $(model.n_features)")
println("  Output dimension: $(model.n_output)")
println("  Hidden layers: $(model.layers)")
println()

# ============================================================================
# STEP 2: Load DCOPF Test Data
# ============================================================================

println("STEP 2: Loading DCOPF test data")
println("-" ^ 80)

# Path to DCOPF dataset
data_file = joinpath(@__DIR__, "..", "icnn", "data", "data_pglib_opf_case118_ieee.bson")

if !isfile(data_file)
    println("ERROR: DCOPF dataset not found at:")
    println("  $data_file")
    println()
    println("Please generate the dataset by running:")
    println("  julia icnn/data/Generate_DCOPF.jl")
    println()
    exit(1)
end

# Load and prepare dataset (using same preprocessing as training)
dataset = prepare_dcopf_dataset(
    data_file;
    train_ratio=0.8,
    normalize_method=:none,
    shuffle=true,
    seed=42
)

X_test = dataset.X_test
Y_test = dataset.Y_test
n_features = dataset.n_features
scaler_Y = dataset.scaler_Y

println("✓ Data loaded successfully!")
println()
println("Dataset statistics:")
println("  Test samples: $(size(X_test, 1))")
println("  Features: $n_features")
println("  Y range (normalized): [$(round(minimum(Y_test), digits=4)), $(round(maximum(Y_test), digits=4))]")

# Compute model performance on test set for context
Y_pred = predict(model, X_test)
test_mse = mean((Y_pred .- Y_test) .^ 2)
test_mae = mean(abs.(Y_pred .- Y_test))

println()
println("Model test performance:")
@printf("  MSE:  %.6e\n", test_mse)
@printf("  MAE:  %.6e\n", test_mae)
println()

# ============================================================================
# STEP 3: Select Test Instance
# ============================================================================

println("STEP 3: Selecting test instance")
println("-" ^ 80)

# Strategy: Find an instance with high cost (good candidate for reduction)
# This makes the counterfactual scenario realistic: "How can we reduce cost?"

Y_pred_test = predict(model, X_test)
Y_pred_denorm = denormalize_output(Y_pred_test, scaler_Y)

# Find instances in top 25% of predicted costs
high_cost_threshold = quantile(Y_pred_denorm[:, 1], 0.75)
high_cost_indices = findall(y -> y >= high_cost_threshold, Y_pred_denorm[:, 1])

# Pick one from high-cost instances
test_idx = high_cost_indices[min(5, length(high_cost_indices))]  # 5th highest or available

x_factual = Float32.(X_test[test_idx, :])
y_factual_norm = Y_pred_test[test_idx, 1]
y_factual = Y_pred_denorm[test_idx, 1]
y_true = denormalize_output(Y_test[test_idx:test_idx, :], scaler_Y)[1, 1]

println("Selected test instance: #$test_idx")
println()
println("Factual scenario:")
println("  Predicted cost (denormalized): \$$(round(y_factual, digits=2))")
println("  True optimal cost:              \$$(round(y_true, digits=2))")
println("  Prediction error:               \$$(round(abs(y_factual - y_true), digits=2))")
println("  Normalized prediction:          $(round(y_factual_norm, digits=4))")
println()

# ============================================================================
# STEP 4: Define Counterfactual Target
# ============================================================================

println("STEP 4: Defining counterfactual target")
println("-" ^ 80)

# Strategy: Try multiple reduction levels to find achievable target
# Start with 5% (conservative), try up to 15% if feasible

# First, check model's prediction range on test set to set realistic target
y_test_min = minimum(Y_pred_denorm[:, 1])
y_test_max = maximum(Y_pred_denorm[:, 1])

println("Model prediction range (test set): [\$$(round(y_test_min, digits=2)), \$$(round(y_test_max, digits=2))]")
println("Current cost: \$$(round(y_factual, digits=2))")
println()

# Percentage reduction of the cost
reduction_percentage = 0.30
y_target_denorm = y_factual * (1 - reduction_percentage)

# Convert target to normalized space (what the model works with)
# Handle different normalization methods
y_target = Float64(y_target_denorm)

# Epsilon is the tolerance for the target constraint
epsilon = 0.002 * abs(y_target)

println("Counterfactual goal: Reduce operational cost by $(round(reduction_percentage * 100, digits=1))%")
println()
println("Target specification:")
println("  Constraint: f(x) ≤ y_target + ε (CONVEX constraint)")
println("  Target cost (denormalized): \$$(round(y_target_denorm, digits=2))")
println("  Target (normalized):        $(round(y_target, digits=4))")
println("  Upper bound: f(x) ≤         $(round(y_target + epsilon, digits=4))")
println()
println("Question: What demand changes achieve this cost reduction?")
println()

# ============================================================================
# STEP 5: Configure Counterfactual Parameters
# ============================================================================

println("STEP 5: Configuring OA parameters")
println("-" ^ 80)

# Parameter choices explained:

# Sparsity weight: Balance between distance and number of changed features
# Higher = fewer features changed but possibly larger changes
# For DCOPF: 0.05 encourages sparse solutions (change few buses)
sparsity_weight = 0.05

# Bounds: For standardized data, use actual range from training data
# Standardization doesn't bound to [0, 1], so we need actual min/max
x_min = minimum(X_test)
x_max = maximum(X_test)
# Add some margin for exploration
x_bounds = (Float64(x_min), Float64(x_max + 0.5))

println("Input feature range (from test data):")
println("  Min: $(round(x_min, digits=4))")
println("  Max: $(round(x_max, digits=4))")
println("  Bounds used: [$(round(x_bounds[1], digits=2)), $(round(x_bounds[2], digits=2))]")
println()

# Immutable indices: In DCOPF, we might want to fix certain bus demands
# For this example, allow all features to change
immutable_indices = Int[]
# Example of fixing first 5 features: immutable_indices = [1, 2, 3, 4, 5]

# Iteration and time limits
max_iterations = 50
time_limit_per_iter = 60.0  # seconds per MILP solve

# Convergence tolerance
tolerance = 1e-4

println("OA algorithm parameters:")
println("  Sparsity weight:         $sparsity_weight")
println("  Input bounds:            [$(round(x_bounds[1], digits=2)), $(round(x_bounds[2], digits=2))]")
println("  Immutable features:      $(length(immutable_indices))")
println("  Max iterations:          $max_iterations")
println("  Time limit per iter:     $(time_limit_per_iter)s")
println("  Convergence tolerance:   $tolerance")
println()

# ============================================================================
# STEP 6: Generate Counterfactual
# ============================================================================

println("STEP 6: Running OA counterfactual generation")
println("=" ^ 80)
println()

start_time = time()

result = generate_counterfactual_oa(
    model,
    x_factual,
    y_target;
    epsilon=epsilon,
    sparsity_weight=sparsity_weight,
    x_bounds=x_bounds,
    immutable_indices=immutable_indices,
    max_iterations=max_iterations,
    time_limit_per_iter=time_limit_per_iter,
    tolerance=tolerance,
    verbose=true  # Show iteration-by-iteration progress
)

total_time = time() - start_time

println()
println("=" ^ 80)

# ============================================================================
# STEP 7: Validate and Report Results
# ============================================================================

println()
println("STEP 7: Validation and results")
println("=" ^ 80)
println()

# If infeasible, try alternative: INCREASE cost instead (opposite direction)
if result[:status] == :infeasible
    println("⚠ Cost reduction scenario was infeasible")
    println()
    println("Trying alternative scenario: INCREASE cost by $(round(reduction_percentage * 100, digits=1))%")
    println("-" ^ 80)

    # Try increasing instead - this means finding configurations with cost UP TO the new target
    y_target_denorm_alt = y_factual * (1 + reduction_percentage)
    y_target_alt = Float64(y_target_denorm_alt)
    epsilon_alt = 0.02 * abs(y_target_alt)
    epsilon_alt = max(epsilon_alt, 0.01)

    println("Alternative target: \$$(round(y_target_denorm_alt, digits=2)) (normalized: $(round(y_target_alt, digits=4)))")
    println("Constraint: f(x) ≤ $(round(y_target_alt + epsilon_alt, digits=4)) (still CONVEX)")
    println()

    # Re-run OA with alternative target
    result = generate_counterfactual_oa(
        model,
        x_factual,
        y_target_alt;
        epsilon=epsilon_alt,
        sparsity_weight=sparsity_weight,
        x_bounds=x_bounds,
        immutable_indices=immutable_indices,
        max_iterations=max_iterations,
        time_limit_per_iter=time_limit_per_iter,
        tolerance=tolerance,
        verbose=true
    )

    # Update variables for reporting
    reduction_percentage = -reduction_percentage  # Negative = increase
    y_target = y_target_alt
    y_target_denorm = y_target_denorm_alt
    epsilon = epsilon_alt

    println()
    println("=" ^ 80)
    println()
end

if result[:status] == :optimal
    # Extract solution
    x_cf = result[:counterfactual]
    y_cf_norm = result[:prediction]
    distance_l1 = result[:distance]
    num_changed = result[:num_changed]
    changed_indices = result[:changed_indices]

    # Denormalize prediction
    y_cf = denormalize_output([y_cf_norm;;], scaler_Y)[1, 1]

    # Compute statistics
    achieved_reduction = (y_factual - y_cf) / y_factual
    target_error_norm = abs(y_cf_norm - y_target)
    target_error_denorm = abs(y_cf - y_target_denorm)

    println("✓ SUCCESS: Counterfactual found!")
    println()
    println("=" ^ 80)
    println("OPTIMIZATION SUMMARY")
    println("=" ^ 80)
    println()
    println("Status:                    $(result[:status])")
    println("Iterations:                $(result[:iterations])")
    println("Solve time:                $(round(result[:solve_time], digits=2))s")
    println("Best objective:            $(round(result[:upper_bound], digits=4))")
    println()

    println("=" ^ 80)
    println("COUNTERFACTUAL QUALITY")
    println("=" ^ 80)
    println()

    println("Distance metrics:")
    println("  L1 distance (normalized): $(round(distance_l1, digits=4))")
    println("  Features changed:         $num_changed / $n_features ($(round(100 * num_changed / n_features, digits=1))%)")
    println("  Sparsity:                 $(num_changed == 0 ? "Perfect" : num_changed <= 5 ? "Excellent" : num_changed <= 10 ? "Good" : "Moderate")")
    println()

    println("Target matching:")
    println("  Target (normalized):      $(round(y_target, digits=4))")
    println("  Achieved (normalized):    $(round(y_cf_norm, digits=4))")
    println("  Error (normalized):       $(round(target_error_norm, digits=6))")
    println("  Within epsilon?           $(target_error_norm <= epsilon ? "✓ YES" : "✗ NO")")
    println()

    println("Cost comparison (original scale):")
    println("  Factual cost:             \$$(round(y_factual, digits=2))")
    println("  Target cost:              \$$(round(y_target_denorm, digits=2))")
    println("  Counterfactual cost:      \$$(round(y_cf, digits=2))")

    if reduction_percentage >= 0
        println("  Achieved reduction:       $(round(achieved_reduction * 100, digits=1))%")
        println("  Target reduction:         $(round(reduction_percentage * 100, digits=1))%")
        println("  Cost savings:             \$$(round(y_factual - y_cf, digits=2))")
    else
        achieved_increase = (y_cf - y_factual) / y_factual
        println("  Achieved increase:        $(round(achieved_increase * 100, digits=1))%")
        println("  Target increase:          $(round(-reduction_percentage * 100, digits=1))%")
        println("  Cost increase:            \$$(round(y_cf - y_factual, digits=2))")
    end
    println()

    # ========================================================================
    # STEP 8: Detailed Feature Analysis
    # ========================================================================

    println("=" ^ 80)
    println("FEATURE CHANGES ANALYSIS")
    println("=" ^ 80)
    println()

    if num_changed == 0
        println("No features changed (already at target)")
    else
        # Compute change magnitudes
        deltas = x_cf .- x_factual
        abs_deltas = abs.(deltas)

        # Sort by magnitude of change
        sorted_indices = sortperm(abs_deltas[changed_indices], rev=true)
        top_changes = changed_indices[sorted_indices]

        println("Top $(min(20, num_changed)) changed features:")
        println()
        println("  Rank | Feature | Factual | Counterfactual |  Change  | % Change")
        println("  -----|---------|---------|----------------|----------|----------")

        for (rank, feat_idx) in enumerate(top_changes[1:min(20, num_changed)])
            fact_val = x_factual[feat_idx]
            cf_val = x_cf[feat_idx]
            delta = cf_val - fact_val
            pct_change = abs(delta) / (abs(fact_val) + 1e-8) * 100

            @printf("   %2d  |  %4d   | %7.4f | %7.4f        | %+7.4f | %6.1f%%\n",
                   rank, feat_idx, fact_val, cf_val, delta, pct_change)
        end

        if num_changed > 20
            println("  ...  (showing top 20 of $num_changed changed features)")
        end

        println()

        # Summary statistics
        println("Change statistics:")
        println("  Mean absolute change:     $(round(mean(abs_deltas[changed_indices]), digits=4))")
        println("  Max absolute change:      $(round(maximum(abs_deltas[changed_indices]), digits=4))")
        println("  Std of changes:           $(round(std(deltas[changed_indices]), digits=4))")

        # Direction analysis
        n_increased = sum(deltas[changed_indices] .> 0)
        n_decreased = sum(deltas[changed_indices] .< 0)
        println()
        println("Change direction:")
        println("  Features increased:       $n_increased")
        println("  Features decreased:       $n_decreased")
    end

    println()

    # ========================================================================
    # STEP 9: Interpretation for DCOPF
    # ========================================================================

    println("=" ^ 80)
    println("INTERPRETATION FOR DCOPF")
    println("=" ^ 80)
    println()

    println("What does this counterfactual tell us?")
    println()

    if reduction_percentage >= 0
        println("The counterfactual identifies demand modifications that achieve a")
        println("$(round(reduction_percentage * 100, digits=1))% cost reduction in the power system.")
    else
        println("The counterfactual identifies demand modifications that result in a")
        println("$(round(-reduction_percentage * 100, digits=1))% cost increase in the power system.")
        println("(This demonstrates the flexibility of the method for what-if analysis)")
    end

    println()
    println("Key insights:")
    println("  • Only $num_changed out of $n_features demand values need to change")
    println("  • This provides actionable recommendations for demand management")
    println("  • Changes are in normalized space - denormalization needed for real values")
    println("  • Sparse solution indicates targeted interventions are sufficient")
    println()

    if num_changed > 0 && num_changed <= n_features / 2
        println("The high sparsity ($num_changed features) suggests focused demand-side")
        println("management at specific buses is more effective than system-wide changes.")
    elseif num_changed > n_features / 2
        println("The moderate sparsity ($num_changed features) suggests system-wide")
        println("adjustments may be necessary for this level of cost change.")
    end

    println()

    # ========================================================================
    # STEP 10: Algorithm Performance Analysis
    # ========================================================================

    println("=" ^ 80)
    println("ALGORITHM PERFORMANCE")
    println("=" ^ 80)
    println()

    println("OA convergence:")
    println("  Total iterations:         $(result[:iterations])")
    println("  Total solve time:         $(round(result[:solve_time], digits=2))s")
    println("  Avg time per iteration:   $(round(result[:solve_time] / result[:iterations], digits=2))s")
    println("  Best objective:           $(round(result[:upper_bound], digits=6))")
    println()

    if haskey(result, :iteration_history)
        history = result[:iteration_history]

        # Count feasible iterations
        n_feasible = sum([iter.feasible for iter in history])
        first_feasible = findfirst([iter.feasible for iter in history])

        println("Convergence metrics:")
        println("  Feasible iterations:      $n_feasible / $(length(history))")
        println("  First feasible at:        $(first_feasible !== nothing ? "iter $first_feasible" : "none")")

        # Bound progression
        if length(history) >= 2 && history[end].UB < Inf
            initial_ub = history[1].UB
            final_ub = history[end].UB
            
            if isfinite(initial_ub) && isfinite(final_ub)
                println("  Best objective (initial): $(round(initial_ub, digits=4))")
                println("  Best objective (final):   $(round(final_ub, digits=6))")
            end
        end

        println()
        println("Iteration history (first 5 and last 5):")
        println()
        println("  Iter | Master obj |    UB    |  f(x)   | Target err | Feasible")
        println("  -----|------------|----------|---------|------------|----------")

        # Show first 5
        for iter in history[1:min(5, length(history))]
            feas = iter.feasible ? "✓" : "✗"
            @printf("   %2d  | %10.4f | %8.4f | %7.4f | %10.6f |    %s\n",
                   iter.iteration, iter.obj_k, iter.UB, iter.f_k, iter.target_error, feas)
        end

        # Show last 5 if more than 10 iterations
        if length(history) > 10
            println("  ...  |    ...     |    ...   |   ...   |    ...     |   ...")
            for iter in history[end-4:end]
                feas = iter.feasible ? "✓" : "✗"
                @printf("   %2d  | %10.4f | %8.4f | %7.4f | %10.6f |    %s\n",
                       iter.iteration, iter.obj_k, iter.UB, iter.f_k, iter.target_error, feas)
            end
        elseif length(history) > 5
            # Show remaining if between 5 and 10
            for iter in history[6:end]
                feas = iter.feasible ? "✓" : "✗"
                @printf("   %2d  | %10.4f | %8.4f | %7.4f | %10.6f |    %s\n",
                       iter.iteration, iter.obj_k, iter.UB, iter.f_k, iter.target_error, feas)
            end
        end
    end

    println()

elseif result[:status] == :already_at_target
    println("✓ Factual instance already satisfies target!")
    println()
    println("No changes needed - the current demand configuration")
    println("already achieves the target cost.")

else
    println("✗ No counterfactual found")
    println()
    println("Status: $(result[:status])")
    println("Iterations: $(result[:iterations])")
    println("Solve time: $(round(result[:solve_time], digits=2))s")
    println()

    if result[:status] == :infeasible
        println("Possible reasons for infeasibility:")
        println("  • Target may be unachievable given input bounds")
        println("  • Immutability constraints may be too restrictive")
        println("  • Epsilon tolerance may be too tight")
        println()
        println("Suggestions:")
        println("  • Try relaxing epsilon (currently $(round(epsilon, digits=4)))")
        println("  • Check if target is within model's prediction range")
        println("  • Reduce number of immutable features")
    elseif result[:status] == :no_solution
        println("Algorithm reached max iterations without finding feasible solution.")
        println()
        println("Suggestions:")
        println("  • Increase max_iterations (currently $max_iterations)")
        println("  • Increase time_limit_per_iter (currently $(time_limit_per_iter)s)")
        println("  • Relax epsilon tolerance")
    end

    if haskey(result, :iteration_history) && length(result[:iteration_history]) > 0
        println()
        println("Last 5 iterations:")
        history = result[:iteration_history]
        for iter in history[max(1, end-4):end]
            @printf("  Iter %2d: obj=%.4f UB=%.4f f(x)=%.4f err=%.4f\n",
                   iter.iteration, iter.obj_k, iter.UB, iter.f_k, iter.target_error)
        end
    end
end

println()
println("=" ^ 80)
println("EXAMPLE COMPLETE")
println("=" ^ 80)
println()

if result[:status] == :optimal
    println("✓ Successfully demonstrated OA counterfactual generation on DCOPF data")
    println()
    println("Next steps:")
    println("  • Denormalize counterfactual to get actual demand values")
    println("  • Verify with actual DCOPF solver if needed")
    println("  • Try different sparsity weights for more/fewer changes")
    println("  • Experiment with different target reductions")
    println("  • Add immutability constraints for realistic scenarios")
else
    println("The example completed but no counterfactual was found.")
    println("Try adjusting parameters as suggested above.")
end

println()
