"""
Train StandardNN on AC Optimal Power Flow data.

This example demonstrates training a standard neural network (non-convex)
for regression on ACPM (AC Power Model) data:
- Input (X): Demand vectors (concatenated P and Q for each bus)
- Output (Y): Optimal AC objective values (scalar)

Unlike DCPM, the ACPM problem is NON-CONVEX due to the nonlinear AC power
flow equations. Therefore, we use a standard neural network (StandardNN)
instead of an Input Convex Neural Network.

Key differences from FICNN training:
1. Use StandardNN instead of FICNN
2. Set is_convex=false (no convexity enforcement)
3. Load ACPM data (AC objectives) instead of DCPM data
"""

using Pkg
Pkg.activate(".")

include("../ICNN.jl")
using .ICNN

using Random
using Statistics
using Printf

println("=" ^ 70)
println("Training StandardNN on AC Optimal Power Flow Data")
println("=" ^ 70)

# ============================================================================
# 1. Configuration
# ============================================================================

# Data file path (generated by icnn/data/Generate_DCOPF.jl with mode="AC+DC")
# You need to first run Generate_DCOPF.jl to create this file
data_file = "icnn/data/data_pglib_opf_case118_ieee_AC+DC.bson"

# Model hyperparameters
hidden_sizes = [500, 500]  # Standard architecture
learning_rate = 1f-3       # Adam learning rate
batch_size = 32
epochs = 50

# Data preprocessing
normalize_method = :none  # Options: :standardize, :minmax, :none
train_ratio = 0.8

# Training options
is_convex = false  # IMPORTANT: Set to false for StandardNN (no convexity constraints)
save_dir = "./tmp/acpm_standard_nn_experiment"
collect_metrics = true

println("\n📋 Configuration:")
println("   Data file: $data_file")
println("   Model: StandardNN (non-convex)")
println("   Hidden layers: $hidden_sizes")
println("   Learning rate: $learning_rate")
println("   Batch size: $batch_size")
println("   Epochs: $epochs")
println("   Normalization: $normalize_method")
println("   Train/Test split: $(train_ratio)/$(1-train_ratio)")
println("   Convexity constraint: $is_convex (standard NN - no constraints)")

# ============================================================================
# 2. Load and Prepare Data
# ============================================================================

println("\n" * "=" ^ 70)
println("Loading and Preparing ACPM Data")
println("=" ^ 70)

if !isfile(data_file)
    error("""
    Data file not found: $data_file

    Please first generate the data by running:
        julia icnn/data/Generate_DCOPF.jl

    Make sure to set mode="AC+DC" in the script to generate AC data.
    This will create the BSON file with both AC and DC OPF problem instances.
    """)
end

# Load and prepare dataset
dataset = prepare_acpm_dataset(
    data_file;
    train_ratio=train_ratio,
    normalize_method=normalize_method,
    shuffle=true,
    seed=42
)

# Extract dataset components
X_train = dataset.X_train
Y_train = dataset.Y_train
X_test = dataset.X_test
Y_test = dataset.Y_test
n_features = dataset.n_features

println("\n✅ Data loaded successfully!")
println("   Features dimension: $n_features")
println("   Training samples: $(size(X_train, 1))")
println("   Test samples: $(size(X_test, 1))")
println("   Problem type: NON-CONVEX (AC Power Flow)")

# ============================================================================
# 3. Create Model
# ============================================================================

println("\n" * "=" ^ 70)
println("Creating StandardNN Model")
println("=" ^ 70)

model = StandardNN(n_features, 1; hidden_sizes=hidden_sizes)

println("\n✅ Model created!")
println("   Architecture:")
println("      Input: $n_features features")
for (i, size) in enumerate(hidden_sizes)
    println("      Hidden $i: $size units (ReLU)")
end
println("      Output: 1 value (linear)")
println("\n   Trainable parameters:")
println("      Input layer: $(length(model.input_layer.weight)) weights + $(length(model.input_layer.bias)) biases")
for (i, layer) in enumerate(model.hidden_layers)
    n_params = length(layer.weight) + length(layer.bias)
    println("      Hidden $i: $n_params weights (can be positive or negative)")
end

# ============================================================================
# 4. Train Model
# ============================================================================

println("\n" * "=" ^ 70)
println("Training Model")
println("=" ^ 70)

Random.seed!(42)

model = train!(
    model, X_train, Y_train, epochs;
    learning_rate=learning_rate,
    batch_size=batch_size,
    save_dir=save_dir,
    is_convex=is_convex,  # IMPORTANT: false for StandardNN
    X_test=X_test,
    y_test=Y_test,
    collect_metrics=collect_metrics,
    scaler_X=dataset.scaler_X,
    scaler_Y=dataset.scaler_Y
)

println("\n✅ Training completed!")

# ============================================================================
# 5. Evaluate Model
# ============================================================================

println("\n" * "=" ^ 70)
println("Final Evaluation")
println("=" ^ 70)

# Make predictions
y_pred_train = predict(model, X_train)
y_pred_test = predict(model, X_test)

# Calculate metrics
train_mse = mean((y_pred_train .- Y_train) .^ 2)
train_rmse = sqrt(train_mse)
train_mae = mean(abs.(y_pred_train .- Y_train))

test_mse = mean((y_pred_test .- Y_test) .^ 2)
test_rmse = sqrt(test_mse)
test_mae = mean(abs.(y_pred_test .- Y_test))

println("\n📊 Training Set:")
@printf("   MSE:  %.6e\n", train_mse)
@printf("   RMSE: %.6e\n", train_rmse)
@printf("   MAE:  %.6e\n", train_mae)

println("\n📊 Test Set:")
@printf("   MSE:  %.6e\n", test_mse)
@printf("   RMSE: %.6e\n", test_rmse)
@printf("   MAE:  %.6e\n", test_mae)

println("\n📈 Predictions (first 10 samples):")
println("   First 10 predictions vs actual:")
for i in 1:min(10, length(Y_test))
    @printf("      Sample %2d: Pred = %.2f, True = %.2f, Error = %.2f\n",
            i, y_pred_test[i], Y_test[i],
            abs(y_pred_test[i] - Y_test[i]))
end

# Check weight distribution (StandardNN allows negative weights)
println("\n🔧 Weight Distribution Check:")
for (i, layer) in enumerate(model.hidden_layers)
    w = layer.weight
    n_negative = sum(w .< -1e-6)
    println("   Hidden layer $i: $n_negative negative weights (expected for StandardNN)")
    @printf("      Range: [%.6f, %.6f]\n", minimum(w), maximum(w))
end

# ============================================================================
# 6. Save Results
# ============================================================================

println("\n" * "=" ^ 70)
println("Saving Results")
println("=" ^ 70)

println("\n📁 Saved files:")
println("   Best model: $(joinpath(save_dir, "best_model.bson"))")
println("   Final model: $(joinpath(save_dir, "final_model.bson"))")
println("   Training log: $(joinpath(save_dir, "training_log.csv"))")
if collect_metrics
    println("   Metrics: $(joinpath(save_dir, "metrics_julia.json"))")
end

println("\n" * "=" ^ 70)
println("✅ All done!")
println("=" ^ 70)
